;;; emacs-rc-gnus-split.el --- nnmail split rules

;; Copyright (C) 2004 Alex Ott
;;
;; Author: alexott@gmail.com


(setq nnmail-split-methods 'nnmail-split-fancy)
(setq nnmail-split-fancy
      `(| ;; message duplicates
;;	  ("gnus-warning" "duplicat\\(e\\|ion\\) of message" "duplicates")

          ;; catch spam
;;           (subject ".*\\*\\*\\*\\*\\*SPAM\\*\\*\\*\\*\\*.*" "SPAM")
;;           (spam-flag "YES" "SPAM")
;; 					(: spam-stat-split-fancy)
          
          ;; Mailing lists
;; 					(any "ding@\\(gnus.org\\|hpc.uh.edu\\|lists.math.uh.edu\\)" "gnus-ding")
;; 					(any "emacs-devel@gnu.org" "emacs-devel")
;; 					(any "emacs-pretest-bug@gnu.org" "emacs-devel")
;;           (any "\\(jde\\|jde-devel\\|jde-patches\\)@sunsite.dk" "jdee")
;;           (any "emacs-nxml-mode@yahoogroups.com" "nxml-mode")
;;           (any "db2latex-apps@lists.\\(sourceforge\\|sf\\).net" "db2latex")
;;           (any "db2latex-devel@lists.\\(sourceforge\\|sf\\).net" "db2latex")
;;           (any "cedet-devel@lists.\\(sourceforge\\|sf\\).net" "cedet")
;;           (any "cedet-eieio@lists.\\(sourceforge\\|sf\\).net" "cedet")
;;           (any "cedet-semantic@lists.\\(sourceforge\\|sf\\).net" "cedet")
;;           (any "ecb-list@lists.\\(sourceforge\\|sf\\).net" "ecb")
;;           (any "mmm-mode-discuss@lists.\\(sourceforge\\|sf\\).net" "mmm-mode")
;;           (any "xwem-devel@xwem.org" "xwem")
;;           (any "xwem-devel@nongnu.org" "xwem")
;;           (any "w3-dev@gnu.org" "w3-dev")
;;           (any "schematics-users@lists.\\(sourceforge\\|sf\\).net" "schematics")
;;           (any "emacspeak-devel@lists.\\(sourceforge\\|sf\\).net" "emacspeak")
;;           (list-id "cc-mode-help.lists.\\(sourceforge\\|sf\\).net" "cc-mode")
;;           (any "bbdb-info@lists.\\(sourceforge\\|sf\\).net" "bbdb")
;;           (any "psgml-devel@lists.\\(sourceforge\\|sf\\).net" "psgml-devel")
;;           (any "psgml-user@lists.\\(sourceforge\\|sf\\).net" "psgml-user")
;;           (any "squid-announce@squid-cache.org" "squid-users")
;;           (any "squid-dev@squid-cache.org" "squid-devel")
;;           (any "squid-users@squid-cache.org" "squid-users")
;;           (any "dansguardian@yahoogroups.com" "dg")
;;           (any "dansguardianannounce@yahoogroups.com" "dg")
;;           (any "slime-devel@common-lisp.net" "slime")
;;           (any "preview-latex-devel@lists.\\(sourceforge\\|sf\\).net" "preview-latex")
;;           (any "preview-latex-bugs@lists.\\(sourceforge\\|sf\\).net" "preview-latex")
;;           (any "tnt-devel@lists.\\(sourceforge\\|sf\\).net" "tnt-devel")
;;           (any "eicq-devel@lists.\\(sourceforge\\|sf\\).net" "eicq")
;; 					(any "emchat-devel@emchat.org" "eicq")
;; 					(list-id "eicq-devel.eicq.org" "eicq")
;; 					(list-id "eicq-users.eicq.org" "eicq")
;; 					(list-id "eicq-bug.eicq.org" "eicq")
;;           (any "dgav-devel@lists.\\(sourceforge\\|sf\\).net" "dgav-devel")
;; 					(any "dgav-cvs@lists.sourceforge.net" "dgav-devel")
;;           (any "icap-discussions@yahoogroups.com" "icap-discuss")
;;           (any "emms-help@gnu.org" "emms")
;;           (list-id "xtla-el-dev.gna.org" "xtla")
;;           (any "emacs-jabber-general@lists.sourceforge.net" "emacs-jabber")
;;           (any "emacs-wiki-discuss@nongnu.org" "emacs-wiki")
;;           (any "auc-tex@sunsite.dk" "auctex-devel")
;;           (any "auctex@gnu.org" "auctex-devel")
;;           (any "auctex-devel@gnu.org" "auctex-devel")
;;           (list-id "plt-scheme.list.cs.brown.edu" "mzscheme")
;;           (list-id "plt-announce.list.cs.brown.edu" "mzscheme")
;;           (list-id "tramp-devel.nongnu.org" "tramp")
;; 					(any "tramp-devel@nongnu.org" "tramp")
;; 					(any "tramp-devel@gnu.org" "tramp")
;; 					(any "tramp-devel@mail.freesoftware.fsf.org" "tramp")
;;           (any "xemacs-design@xemacs.org" "xemacs-design")
;;           (any "ietf-openproxy@imc.org" "ietf-openproxy")
;;           (any "dansguardian-dev@yahoogroups.com" "dg-devel")
;;           (any "dansguardian-cvs@lists.sourceforge.net" "dg-devel")
;;           (any "googlealerts-noreply@google.com" "google-alerts")
;;           (any "ug-mosug@opensolaris.org" "solaris-mosug")
;;           (any "erc-discuss@gnu.org" "erc")
;;           (any "bbdb-info@lists.sourceforge.net" "bbdb")
;;           (any "muse-el-discuss@gna.org" "muse-el")
;;           (any "planner-el-discuss@gna.org" "planner-el")
;;           (any "asio-users@lists.sourceforge.net" "asio")
;;           (any "dvc-dev@gna.org" "dvc")
;;           (any "bug-cc-mode@gnu.org" "cc-mode")
;;           (any "boost@lists.boost.org" "boost-devel")
;;           (any "boost-users@lists.boost.org" "boost-users")
;;           (any "emacs-jabber-general@lists.sourceforge.net" "emacs-jabber")
;;           (any "xtla-el-dev@gna.org" "xtla")
;;           (any "eicq-devel@eicq.org" "eicq")
;;           (any "squid-dev@squid-cache.org" "squid-devel")
;;           (any "c-icap-users@lists.sourceforge.net" "c-icap")
;;           (any "cc-mode-help@lists.sourceforge.net" "cc-mode")
;;           (any "xwem-devel@xwem.org" "xwem")
;;           (any "soci-users@lists.sourceforge.net" "soci")
;;           (any "fsharp@list.research.microsoft.com" "fsharp")
;;           (any "docs@lists.altlinux.org" "altlinux-docs")
;;           (any "icap-discussions@yahoogroups.com" "icap-discussions")
;;           (any "intro2fp@googlegroups.com" "intro2fp")
;; 					(any "firewall-wizards@listserv.icsalabs.com" "fw-wizards" "fw-wizards")
;; 					(any "firewall-wizards@honor.icsalabs.com" "fw-wizards")
;; 					(any "firewall-wizards@listserv.cybertrust.com" "fw-wizards")
;;           (any "ug-gosug@opensolaris.org" "solaris-gosug")
;;           (any "cedet-semantic@lists.sourceforge.net" "cedet")
;;           (any "funprog-ru@sxemacs.org" "intro2fp")
;;           (any "cpp-netlib-devel@lists.sourceforge.net" "cpp-netlib")
;;           (any "cedet-eieio@lists.sourceforge.net" "cedet")
;;           (any "spirit-general@lists.sourceforge.net" "boost-spirit")
;;           (reply-to ".*@bugs.launchpad.net" "emacs-ubuntu")
;;           (any "google-safe-browsing-api@googlegroups.com" "google-sba")
;; 					(any "openfwtk-devel@lists.sourceforge.net" "openfwtk-devel")
;; 					(any "arabica-devel@lists.sourceforge.net" "arabica-devel")
;; 					(any "websecurity@webappsec.org" "ws-webapps")
;; 					(any "wasc-wafec@webappsec.org" "wasc-wafec")
;;           (any "pcl-ru@googlegroups.com" "pcl-ru")
;          (list-id "" "")
;          (list-id "" "")
;          (list-id "" "")
;          (list-id "" "")

	  ;; catch-all
	  "inbox"))


;;; emacs-rc-gnus-split.el ends here

